apiVersion: v1
kind: ConfigMap
metadata:
  name: june-2022-193064-config
data:
  application.properties: |
    spring.datasource.url=jdbc:h2:mem:testdb
    spring.datasource.username=sa
    spring.jpa.show-sql=false
    spring.h2.console.enabled=true
    spring.thymeleaf.cache=false
    server.port=8081
