apiVersion: apps/v1
kind: Deployment
metadata:
  name: june-2022-193064-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: june-2022-193064-app
  template:
    metadata:
      labels:
        app: june-2022-193064-app
    spec:
      containers:
        - name: june-2022-193064-app
          image: june-2022-193064-app:latest
          ports:
            - containerPort: 8081
          
      

